### ISSUE TITLE
Empty dashboard in browser

### ISSUE THREAD

**Issue by nagashreeck** [Netflix/ice#153] opened 2015-02-24 10:39 UTC
in browser dashboard is empty but in the terminal server is running browse http://localhost:8080/ice

here is ice.properties

here is ice.properties

ice.processor=true
ice.reader=true
ice.reservationCapacityPoller=false
ice.reservationPeriod=threeyear
ice.reservationUtilization=MEDIUM
ice.highstockUrl=http://code.highcharts.com/stock/highstock.js
ice.urlPrefix=
ice.fromEmail=
ice.ondemandCostAlertThreshold=250
ice.ondemandCostAlertEmails=
ice.billing_s3bucketname=netflixice
ice.billing_s3bucketprefix=,
ice.billing_payerAccountId=,123456789013
ice.billing_accessRoleName=,ice
ice.startmillis=1364774400000
ice.companyName=Bworks
ice.work_s3bucketname=netflixice
ice.work_s3bucketprefix=ice/
ice.processor.localDir=/mnt/ice_processor
ice.reader.localDir=/mnt/ice_reader
ice.monthlycachesize=12

**Comment by vfilanovsky** [comment] 2015-02-24 18:52
Duplicate of #150. If you have anything to add to it, please reopen that issue and comment on it.

**Closed by vfilanovsky** 2015-02-24 18:52 UTC
